---
- name: Update system packages
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_os_family == "Debian"

- name: Install Docker if not installed
  apt:
    name: docker.io
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Deploy Application Container
  docker_container:
    name: devops_api
    image: "marifervl/devops-chronicles:latest"
    state: started
    restart_policy: always
    published_ports:
      - "5000:5000"
    env:
      FLASK_ENV: "production"  
      DB_HOST: "rds_endpoint"  
      DB_USER: "{{ lookup('aws_ssm', '/devops/DB_USER') }}"
      DB_PASS: "{{ lookup('aws_ssm', '/devops/DB_PASS') }}"
      DB_NAME: "{{ lookup('aws_ssm', '/devops/DB_NAME') }}"
      DB_ROOT_PASS: "{{ lookup('aws_ssm', '/devops/DB_ROOT_PASS') }}"
