FROM jenkins/jenkins:lts

USER root

RUN apt update && \
    apt install -y docker.io unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm -rf awscliv2.zip aws

RUN usermod -aG docker jenkins

USER jenkins
